# Generated by Django 4.0.4 on 2022-05-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adBuilder', '0002_adbuilder_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adbuilder',
            table='adDescription',
        ),
    ]
